config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index  do

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[ show update ] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
      resources :gists, only: %i[index]
      resources :badges
  end

  resources :feedback, only: %i[new create]

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :achievements, dependent: :destroy
  has_many :users, through: :achievements

  validates :title, presence: true
  validates :img, presence: true

  enum rule: {
    no_rule: 0,
    first_attempt_success: 1,
    all_by_category: 2,
    all_by_level: 3
  }

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
    @badge
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success')
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :rule, :img, :rule_value)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
    @badges_distinct = current_user.badges.distinct
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badge_helper.rb
module BadgeHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><%= image_tag badge.img, size: 50 %></td>
  <td class="align-middle"><%= badge.rule %> - <%= badge.rule_value %></td>
  <td class="align-middle"><%= link_to t('.show_link'), admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('.edit_link'), edit_admin_badge_path(badge) %></td>
  <td class="align-middle">
    <%= link_to t('.delete_link'), admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('.delete_notice') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="container">
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <div class="form-group">
  <div class="mb-3 w-25">
    <%= form.label :title, t(".title") %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3 w-25">
    <%= form.label :img, t(".img") %>
    <%= form.text_field :img, class: 'form-control' %>
  </div>

  <div class="mb-3 w-25">
    <%= form.label :rule, t(".rule") %>
    <%= form.select :rule, options_for_select(
            Badge.rules.map { |key, value| [key.humanize, Badge.rules.key(value)] }, @badge.rule),
            { prompt: t(".promtp") }, class: 'form-control' %>
  </div>

  <div class="mb-3 w-25">
    <%= form.label :rule_value, t(".rule_value") %>
    <%= form.text_field :rule_value, class: 'form-control' %>
  </div>
  <p><%= t(".rule_option")%></p>

  <p><%= form.submit t(".save") %></p>
  </div>
<%end%>
<%= link_to t('.badge'), admin_badges_path, class: "btn btn-primary" %>
<%= link_to t('.test'), admin_tests_path, class:"btn btn-success" %>
</div>

app/views/admin/badges/edit.html.erb
<div class="container">
  <h1><%= t(".header")%> "<%= @badge.title %>"</h1>
  <%= render 'form' %>
</div>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3 mx-3">
  <div class="col col-md-12">

    <h1><%= t('.header') %></h1>

    <p>
      <%= link_to t('.new_badge_link'), new_admin_badge_path, class: 'btn btn-primary' %>
      <%= link_to t('.test'), admin_tests_path, class:"btn btn-success" %>
    </p>

    <%= render 'shared/errors', resource: @badge %>

    <div class="card border-primary">

      <table class="table table-striped md-6">
        <thead>
          <tr>
            <th><%= t('.badge_title') %></th>
            <th><%= t('.image') %></th>
            <th><%= t('.rule') %></th>
            <th colspan="3"><%= t('.action') %></th>
          </tr>
        </thead>
        <tbody>
        <%= render @badges %>
      </table>
    </div>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="container">
  <h1><%= t(".header") %></h1>
  <%= render 'form' %>
</div>

app/views/admin/badges/show.html.erb
<div class="container">
<h2><%= t('.header') %></h2>
<p><%= @badge.title %></p>
<p><%= @badge.rule %> - <%= @badge.rule_value %></p>
<%= image_tag @badge.img, size: 120 %>
<div class="mt-4">
<%= link_to t('.edit_link'), edit_admin_badge_path(@badge), class: "btn btn-outline-primary" %>
<%= link_to t('.delete_link'), admin_badge_path(@badge),
            method: :delete,
            data: { confirm: t('.delete_notice')
            }, class: "btn btn-outline-danger"  %>
<%= link_to t('.back'), admin_badges_path, class: "btn btn-outline-info" %>
</div>
</div>