config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index  do

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[ show update ] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
      resources :gists, only: %i[index]
      resources :badges
  end

  resources :feedback, only: %i[new create]

end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/admin.rb
class Admin < User
#  has_many :authored_tests, class_name: :Test, foreign_key: :user_id

#  validates :first_name, presence: true
#  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validation_count_answers

  private

  def validation_count_answers
    errors.add(:base, 'Count answers must be less then 4') if question.answers.count > 3
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :achievements, dependent: :destroy
  has_many :users, through: :achievements

  validates :title, presence: true
  validates :img, presence: true

  enum rule: {
    no_rule: 0,
    first_attempt_success: 1,
    all_by_category: 2,
    all_by_level: 3
  }

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: 'ASC')}

  validates :title, presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  def question_title
    self.question.body.truncate(25)
  end

  def hash_title
    self.url.split('/').last
  end
end

app/models/progress.rb
class Progress < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy
  validates :body, presence: true

end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User'

  scope :easy_test, -> { where(level: 0..1) }
  scope :middle_test, -> { where(level: 2..4) }
  scope :hard_test, -> { where(level: 5..Float::INFINITY) }

  scope :category_name, -> (name) { joins(:category).where(category: { title: name }) }
  scope :sort_title, -> { order(title: 'DESC') }

  scope :visible, -> { where(visible: true) }
  scope :test_on_category, -> (category) {joins(:category).where(categories: { title: category })}

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :level_value

  def self.category_sort(name)
    Test.category_name(name).sort_title.pluck('title')
  end

  def deadline_time
    self.timing*60
  end

  private

  def level_value
    errors.add(:test, "Level must be in (1,2,3) range") unless [1,2,3].include? self.level
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: :current_question_id, optional: true

  before_validation :before_validation_set_question, on: [:create, :update]

  SUCCESS_VALUE = 85

  scope :passed, -> { where(passed: true) }

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def current_question_num
    return test_questions_order.index(current_question) + 1 if current_question.present?
  end

  def questions_total_number
    test.questions.count
  end

  def passage_success?
    rate_of_completed_questions >= SUCCESS_VALUE
  end

  def rate_of_completed_questions
    count = questions_total_number
    result = count.zero? ? 0 : (correct_questions * 100 / count)
  end

  def current_progress
    if test.questions.count == 0
      return 0
    else
      (current_question_num.to_f / test.questions.count * 100).round
    end
  end

  def pass
    update_column(:passed, true) if self.passage_success?
  end

  def passed_time
    Time.now - self.created_at
  end

  private

  def before_validation_set_question
    self.current_question = (self.current_question.nil? ? test_questions_order.first : next_question)
  end

  def test_questions_order
    self.test.questions.order(:id)
  end

  def correct_answer?(answer_ids)
    answer_ids.present? && correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    self.current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: :Test, inverse_of: :author, foreign_key: :author_id
  has_many :gists, dependent: :destroy
  has_many :achievements, dependent: :destroy
  has_many :badges, through: :achievements

 # EMAIL_FORMAT = /[A-Z0-9._%+-]+@([A-Z0-9][-A-z0-9]+\.)+[A-z]{2,4}/i

  validates :email, presence: true, uniqueness: true

  def difficulty(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :find_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_test_not_found

  def index
    @tests = Test.visible
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_test_not_found
    render plain: "Test not found"
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.now.year
  end

  def github(name, repository)
    "https://github.com/#{name}/#{repository}"
  end
end

app/helpers/badge_helper.rb
module BadgeHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    "#{question.persisted? ? 'Edit' : 'Create new'} #{question.test.title} Question"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = {1 => :easy, 2 => :middle, 3=> :hard}.freeze

  def test_level(test)
    case test.level
    when 0..1
      'easy'
    when 2..4
      'middle'
    else
      'hard'
    end
  end

  def test_count_questions(test)
    test.questions.count
  end

  def test_category(test)
    test.category.title
  end

  def test_author(test)
    test.author.name
  end

  def format_time(time)
    minutes = ((time % 3600) / 60).to_i
    seconds = ((time % 3600) % 60).to_i
    "#{sprintf '%02d', minutes}:#{sprintf '%02d', seconds}"
  end

end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to 'Gists', admin_gists_path %>
  <%= t('.title') %>

  <span class="navbar-text">
    <%= t('.welcome') %> <b class="navbar-text"><%= current_user.email %></b> Guru | <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'link-primary'  %>
  </span>

  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'admin/nav' %>  
    <%= render 'shared/flash' %>        
    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/nav' %>  
    <div class="container">
    <%= render 'shared/flash' %>        
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'alert alert-danger resource-errors', role: 'alert', data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>  
<% end %>  

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= content_tag :p, message.html_safe, class: "flash #{key}" %>
  </div>
<% end %>

app/views/shared/_footer.en.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-text">
	<p><%= current_year %><br>
	Author: Anton Spiridonov<br>
	Project TestGuru on creating and passing tests on <%= link_to 'GitHub', github('kerni2', 'RoR-base') %></a><br>
	Educational project in an online school Thinknetica <a href="https://www.thinknetica.com" target="_blank">www.thinknetica.com</a><br></p>
	<%= link_to 'Leave feedback', new_feedback_path %>
  </span>
</nav>

app/views/shared/_footer.ru.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-text">
	<p><%= current_year %><br>
	Автор: Антон Спиридонов<br>
	Проект TestGuru по созданию и прохождению тестов на <%= link_to 'GitHub', github('kerni2', 'RoR-base') %></a><br>
	Учебный проект в онлайн-школе Thinknetica <a href="https://www.thinknetica.com" target="_blank">www.thinknetica.com</a><br></p>
	<%= link_to 'Оставить отзыв', new_feedback_path %>
  </span>
</nav>

app/views/shared/_header.en.html.erb
<header>
  <h1><%= link_to 'TestGuru', root_path %></h1>

 <% if user_signed_in? %>
      <p class="nav user">Welcome,<b><%= current_user.email %> Guru |</b>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </p>
  <% else %>
    <%= link_to 'Register', new_user_registration_path %> |
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
</header>
<hr/>

app/views/shared/_header.html.erb
<header>
  <h1><%= link_to 'TestGuru', root_path %></h1>

 <% if user_signed_in? %>
      <p class="nav user">Welcome,<b><%= current_user.email %> Guru |</b>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </p>
  <% else %>
    <%= link_to 'Register', new_user_registration_path %> |
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
</header>
<hr/>

app/views/shared/_header.ru.html.erb
<header>
  <h1><%= link_to 'TestGuru', root_path %></h1>

 <% if user_signed_in? %>
      <p class="nav user">Добро пожаловать, Гуру <b><%= current_user.email %>  |</b>
      <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      </p>
  <% else %>
    <%= link_to 'Регистрация', new_user_registration_path %> |
    <%= link_to 'Войти', new_user_session_path %>
  <% end %>
</header>
<hr/>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">  
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <%= link_to t('.badges'), badges_path, class: "btn btn-warning" %>
    <span class="navbar-text">
        <% if user_signed_in? %>
          <%= t('shared.nav.welcome') %><b><%= current_user.email %></b> |
          <%= link_to t('shared.nav.logout'), destroy_user_session_path, method: :delete %>
          <% if current_user.admin? %>
              <%= link_to t('shared.nav.admin_panel'), admin_tests_path, class: "nav-link" %>
          <% end %>          
        <% else %>
          <%= link_to 'Log in', new_session_path(resource_name) %> |
          <%= link_to 'Sign up', new_registration_path(resource_name) %>
        <% end %>
    </span>
  </div>
</nav>