config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index  do

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[ show update ] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
      resources :gists, only: %i[index]
      resources :badges
  end

  resources :feedback, only: %i[new create]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy
  validates :body, presence: true

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: :current_question_id, optional: true

  before_validation :before_validation_set_question, on: [:create, :update]

  SUCCESS_VALUE = 85

  scope :passed, -> { where(passed: true) }

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def current_question_num
    return test_questions_order.index(current_question) + 1 if current_question.present?
  end

  def questions_total_number
    test.questions.count
  end

  def passage_success?
    rate_of_completed_questions >= SUCCESS_VALUE
  end

  def rate_of_completed_questions
    count = questions_total_number
    result = count.zero? ? 0 : (correct_questions * 100 / count)
  end

  def current_progress
    if test.questions.count == 0
      return 0
    else
      (current_question_num.to_f / test.questions.count * 100).round
    end
  end

  def pass
    update_column(:passed, true) if self.passage_success?
  end

  def passed_time
    Time.now - self.created_at
  end

  private

  def before_validation_set_question
    self.current_question = (self.current_question.nil? ? test_questions_order.first : next_question)
  end

  def test_questions_order
    self.test.questions.order(:id)
  end

  def correct_answer?(answer_ids)
    answer_ids.present? && correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    self.current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :set_test_passage, only: %i[ show result update gist ]
  before_action :authenticate_user!

  def show

  end

  def result

  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || time_expired?
      TestsMailer.completed_test(@test_passage).deliver_now
      @test_passage.pass
      BadgeService.new(@test_passage).give_badge if @test_passage.passage_success?
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    git_service = GistQuestionService.new(@test_passage.current_question)
    result = git_service.call

    flash_options = if git_service.success?
      @test_passage.current_question.gists.create(user: current_user, url: result.html_url)
      {notice: t('.success', url: result.html_url) }
    else
      {alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  def time_expired?
    @test_passage.passed_time < @test_passage.test.timing
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def save_gist(gist_url)
    current_user.gists.create(question_id: @test_passage.current_question.id, url: gist_url)
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.en.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<p>Test
  <% percent = @test_passage.rate_of_completed_questions %>
  <% if @test_passage.passage_success? %>
    passed <span style="color: chartreuse"><%= percent %></span>
  <% else %>
    failed <span style="color: #cc0000"><%= percent %></span>
  <% end %>
%</p>

<%= link_to 'Back',  tests_path %>

app/views/test_passages/result.html.erb
<h1>The Test <%= @test_passage.test.title %> was completed!</h1>

<p>Test
  <% percent = @test_passage.rate_of_completed_questions %>
  <% if @test_passage.passage_success? %>
    passed <span style="color: chartreuse"><%= percent %></span>
  <% else %>
    failed <span style="color: #cc0000"><%= percent %></span>
  <% end %>
%</p>

<%= link_to 'Back',  tests_path %>

app/views/test_passages/result.ru.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<p>Тест
  <% percent = @test_passage.rate_of_completed_questions %>
  <% if @test_passage.passage_success? %>
    пройден <span style="color: chartreuse"><%= percent %></span>
  <% else %>
    не пройден <span style="color: #cc0000"><%= percent %></span>
  <% end %>
%</p>

<%= link_to 'Назад',  tests_path %>

app/views/test_passages/show.en.html.erb
<div class="row justify-content-center mt-3">
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<p>Question <%= @test_passage.current_question_num %> of <%= @test_passage.questions_total_number %></p>

  <div class="progress mb-4 w-100">
    <%= content_tag :div,
                    class: 'progress-bar bg-info',
                    role: 'progressbar',
                    aria_valuenow: 'width',
                    aria_valuemin: '0',
                    aria_valuemax: '100',
                    data: { current_question: @test_passage.current_question_num,
                    questions_count: @test_passage.questions_total_number } do %>
      <%= @test_passage.current_progress %>%              
    <% end %>
  </div> 

  <div class="timer" data-time="<%= @test_passage.test.deadline_time - @test_passage.passed_time %>"></div>

<div class="card border-primary mb-4">

<b>
  <%= @test_passage.current_question.body %>
</b>
  <div class="form-check">
    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
      <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>    <%= b.label %> <br>
    <% end %>
  </div>
</div>
  <p><%= form.submit 'Next', class: 'btn btn-primary' %></p>
  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
</div>
<% end %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<p>Question <%= @test_passage.current_question_num %> of <%= @test_passage.questions_total_number %></p>
<b>
  <%= @test_passage.current_question.body %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <%= b.check_box id: "answer_ids_#{b.object.id}" %>    <%= b.label %>

  <% end %>

  <p><%= form.submit 'Next' %></p>
<% end %>

app/views/test_passages/show.ru.html.erb
<div class="row justify-content-center mt-3">
<h1>Прохождение теста <%= @test_passage.test.title %></h1>

<p>Вопрос <%= @test_passage.current_question_num %> из <%= @test_passage.questions_total_number %></p>

  <div class="progress mb-4 w-100">
    <%= content_tag :div,
                    class: 'progress-bar bg-info',
                    role: 'progressbar',
                    aria_valuenow: 'width',
                    aria_valuemin: '0',
                    aria_valuemax: '100',
                    data: { current_question: @test_passage.current_question_num,
                    questions_count: @test_passage.questions_total_number } do %>
      <%= @test_passage.current_progress %>%              
    <% end %>
  </div> 

  <div class="timer" data-time="<%= @test_passage.test.deadline_time - @test_passage.passed_time %>"></div>

<div class="card border-primary mb-4">
  
<b>
  <%= @test_passage.current_question.body %>
</b>
  <div class="form-check">
    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
      <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>    <%= b.label %> <br>
    <% end %>
  </div>
</div>
  <p><%= form.submit 'Далее', class:"next-button" %></p>
  <p><%= link_to 'Gist Вопроса', gist_test_passage_path(@test_passage), method: :post %></p>
</div>
<% end %>