config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index  do

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[ show update ] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
      resources :gists, only: %i[index]
      resources :badges
  end

  resources :feedback, only: %i[new create]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy
  validates :body, presence: true

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[index new show create destroy]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_question_not_found

  def index
    @questions = @test.questions
  end

  def show

  end

  def new
    @question = @test.questions.new
  end

  def create
    new_question = @test.questions.new(body: question_params[:body])
    if new_question.save
      redirect_to admin_test_path(@test)
    else
      redirect_to admin_test_path(@test), notice: t('.alert')
    end
  end

  def edit

  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find_by(id: params[:test_id])
  end

  def rescue_question_not_found
    render inline: 'Вопроса с ID: <%= params[:id] %> нет'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_test, only: %i[index create new]
  before_action :find_question, only: %i[show destroy edit update]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render inline: 'Вопроса с ID: <%= params[:id] %> нет'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    "#{question.persisted? ? 'Edit' : 'Create new'} #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.erb
<h2><%= question_header(@question)%></h2>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :body %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('.show'), admin_question_path(question) %></td>
  <td><%= link_to t('.edit'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('.delete'), admin_question_path(question), method: :delete, data: { confirm: t('.confirm') } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>
<%= link_to t('.back'), admin_test_path(@question.test) %>

app/views/admin/questions/index.html.erb
<h1>All questions</h2>
<% @questions.each do |q|%>
<p><%= q.body%>
<a href="<%= admin_question_path(q) %>">show</a>

</p>
<%end%>
<%= link_to "Create new question", new_admin_test_question_path %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>
<p><%= link_to 'Back to Test', admin_test_path(@question.test) %></p>

app/views/admin/questions/show.html.erb
<div class="row justify-content-center mt-3">

  <h2><%= t('.header') %></h2>
  <p>
    <strong><%= t('.body') %></strong>
    <%= @question.body %>
  </p>
  <p>
    <strong><%= t('.title') %></strong>
    <%= @question.test.title %>
  </p>

  <h2><%= t('.answer') %></h2>
  <%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %>

  <div class="card border-primary">

    <ol>
    <%= render @question.answers %>
    </ol>

  </div>
</div>

  <p><%= link_to t('.edit'), edit_admin_question_path(@question) %></p>
  <p><%= link_to t('.delete'), admin_question_path(@question), method: :delete, data: { confirm: t('.confirm') } %></p>
  <p><%= link_to t('.back'), admin_test_path(@question.test) %></p>